sonar.projectKey=Nexus-Project-app_Nexus-Angular-Front
sonar.projectName=Nexus Angular Front
sonar.organization=nexus-projet

# Source code
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/dist/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

# Language
sonar.language=ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Code coverage (if available)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Angular specific
sonar.angular.ngspec=true
